### ISSUE TITLE
numpy dependency not being detected during pip install biogeme

### ISSUE THREAD

**Issue by champost** [michelbierlaire/biogeme#22]
Hello,

There seems to be a issue when running `pip install biogeme` without having installed `numpy` beforehand. I would have expected `pip` to automatically download and install `numpy` if the [dependencies have been correctly specified](https://setuptools.pypa.io/en/latest/userguide/dependency_management.html). 

`numpy` is indeed mentioned as a requirement in several places : 
- https://github.com/michelbierlaire/biogeme/blob/00af1b78868ec92ea44d817078bbea688dcc0569/pyproject.toml#L5
- https://github.com/michelbierlaire/biogeme/blob/00af1b78868ec92ea44d817078bbea688dcc0569/setup.cfg#L44

However, I still run into the issue below :
```
Collecting biogeme
  Downloading biogeme-3.2.10.tar.gz (1.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 16.0 MB/s eta 0:00:00
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [18 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-knq607pg/biogeme_c4432572e1f64d668d85309fa6c242f3/setup.py", line 19, in <module>
          setup()
        File "/tmp/pip-install-knq607pg/biogeme_c4432572e1f64d668d85309fa6c242f3/cysetuptools.py", line 151, in setup
          parsed_setup_cfg = parse_setup_cfg(fp, cythonize=cythonize)
        File "/tmp/pip-install-knq607pg/biogeme_c4432572e1f64d668d85309fa6c242f3/cysetuptools.py", line 224, in parse_setup_cfg
          return _expand_cython_modules(config, cythonize, pkg_config, base_dir)
        File "/tmp/pip-install-knq607pg/biogeme_c4432572e1f64d668d85309fa6c242f3/cysetuptools.py", line 263, in _expand_cython_modules
          module_dict = _expand_one_cython_module(config, section, cythonize,
        File "/tmp/pip-install-knq607pg/biogeme_c4432572e1f64d668d85309fa6c242f3/cysetuptools.py", line 289, in _expand_one_cython_module
          include_dirs = _eval_strings(include_dirs)
        File "/tmp/pip-install-knq607pg/biogeme_c4432572e1f64d668d85309fa6c242f3/cysetuptools.py", line 319, in _eval_strings
          ret.append(eval(value[5:-1]))
        File "<string>", line 1, in <module>
      ModuleNotFoundError: No module named 'numpy'
      ********  Read setup file /tmp/pip-install-knq607pg/biogeme_c4432572e1f64d668d85309fa6c242f3/setup.cfg
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed
× Encountered error while generating package metadata.
╰─> See above for output.
note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

```

**Comment by champost** [comment]
Note that I tested this on several Docker containers.

Installing `biogeme` finally worked when
- I ran `pip install numpy` before `pip install biogeme`
- or `xargs -n 1 -L 1 pip install < requirements.txt` ([which specifies an order](https://stackoverflow.com/questions/5394356/how-to-specify-install-order-for-python-pip)) where `requirements.txt` contained the lines
```
numpy
biogeme
```

**Comment by champost** [comment]
FYI : https://renku.discourse.group/t/pip-install-order-on-renku-using-the-dockerfile/753/2

**Comment by michelbierlaire** [comment]
Version 3.10 was not configured properly. Hopefully, the next version (currently available in the "working" branch) should get it right.
