### ISSUE TITLE
Assertion failed with version 3.2.12

### ISSUE THREAD

**Issue by conema** [michelbierlaire/biogeme#24]
Hi,

I'm getting an assertion failed with the last version (3.2.12). Also using the examples in the repository results in the same error. The assertion doesn't fail in version 3.2.11.

OS: Fedora Linux 38 (Workstation Edition)
Python: 3.11.4
biogeme: 3.2.12
biogeme-optimization: 0.0.4
cythonbiogeme: 1.0.1

The error when executing the b09nested example:
```
Example b09nested 
File biogeme.toml has been created 
*** Initial values of the parameters are obtained from the file __b09nested.iter 
Cannot read file __b09nested.iter. Statement is ignored. 
Optimization algorithm: hybrid Newton/BFGS with simple bounds [simple_bounds] 
** Optimization: Newton with trust region for simple bounds 
/usr/include/c++/13/bits/stl_vector.h:1144: std::vector<_Tp, _Alloc>::const_reference std::vector<_Tp, _Alloc>::operator[](size_type) const [with _Tp = double; _Alloc = std::allocator<double>; const_reference = const double&; size_type = long unsigned int]: Assertion '__n < this->size()' failed.
```

Backtrace:
```
#0  0x00007ffff78b0844 in __pthread_kill_implementation () from /lib64/libc.so.6
#1  0x00007ffff785fabe in raise () from /lib64/libc.so.6
#2  0x00007ffff784887f in abort () from /lib64/libc.so.6
#3  0x00007fffe6edf1e0 in std::__glibcxx_assert_fail(char const*, int, char const*, char const*) () from /lib64/libstdc++.so.6
#4  0x00007fffd1eb7617 in std::vector<double, std::allocator<double> >::operator[] (this=<optimized out>, __n=<optimized out>)
    at /usr/include/c++/13/bits/stl_vector.h:1142
#5  std::vector<double, std::allocator<double> >::operator[] (this=<optimized out>, __n=<optimized out>) at /usr/include/c++/13/bits/stl_vector.h:1142
#6  bioExprPlus::getValueAndDerivatives (this=0x5555587a2fa0, literalIds=..., gradient=<optimized out>, hessian=false) at src/cythonbiogeme/cpp/bioExprPlus.cc:52
#7  0x00007fffd1eaa046 in bioExprLogLogit::getValueAndDerivatives (this=0x555555fbef80, literalIds=std::vector of length 5, capacity 5 = {...}, gradient=true, 
    hessian=false) at src/cythonbiogeme/cpp/bioExprLogLogit.cc:90
#8  0x00007fffd1eda05d in computeFunctionForThread (fctPtr=0x55555879a6e0) at src/cythonbiogeme/cpp/biogeme.cc:399
#9  0x00007ffff78ae907 in start_thread () from /lib64/libc.so.6
#10 0x00007ffff7934870 in clone3 () from /lib64/libc.so.6
```

The problem seems to be around bioExprPlus::getValueAndDerivatives (...) at src/cythonbiogeme/cpp/bioExprPlus.cc:52

I can give you the complete core dump if needed.

Thank you!

**Comment by michelbierlaire** [comment]
Did it happen again with the new version?

**Comment by conema** [comment]
No, working in version 3.2.13. Thanks!
